#!/bin/sh
export ANQI_PUSH_REMOTE="$1"
revisions=""
while read -r local_ref local_oid remote_ref remote_oid; do
  case "$local_oid" in 0000000000000000000000000000000000000000) continue ;; esac
  revisions="$revisions $local_oid"
done
test -n "$revisions" || exit 0
exec /usr/bin/python3 tools/git-private-data-guard.py history $revisions
